### ISSUE TITLE
Override user database credentials

### ISSUE THREAD

**Issue by levkk** [levkk/pgdog#1]
Allow an entry in `users.toml` to define which database credentials to use when connecting to Postgres:

```toml
[[users]]
database_password = "hunter2"
database_user = "admin"
```
